### PR TITLE
Update for Kirby 3

### PR DESCRIPTION
**Pull request by chrispymm**
I'm new to the Kirby ecosystem, (and this is actually my first PR to a 3rd party repo!)
I can see there's been some discussion around the best way of handling Geo stuff in plugins [https://github.com/getkirby/plugin-ideas/issues/45](here), so I hope I'm not out of line? But I needed the functionality, so figured I'd submit the PR.

Only change I wasn't certain about was in the radius filter:

`collection::extractValue($item, $field)`

I replaced this with:

`$collection->getAttribute($item, $field)->value()`

Not if this is the correct / best method to use.

Also, as there's only one branch I've submitte this PR to master, but I'm assuming it'll want to be a separate branch.

### CODE REVIEW

**Comment by bastianallgeier** [comment]
That's so cool! I had that on my list for such a long time. I think it would be best to move this to a new repository in our v3 org. I will do this on Monday.

**Comment by paulrobertlloyd** [comment]
> That's so cool! I had that on my list for such a long time. I think it would be best to move this to a new repository in our v3 org. I will do this on Monday.

@bastianallgeier Did you ever get round to this – I can’t see anything in the new repo.

**Comment by paulrobertlloyd** [comment]
> Only change I wasn't certain about was in the radius filter:
> 
> `collection::extractValue($item, $field)`
> 
> I replaced this with:
> 
> `$collection->getAttribute($item, $field)->value()`
> 
> Not if this is the correct / best method to use.

@chrispymm FWIW, it’s this line that is throwing an error for me:

```
Error thrown with message "Call to a member function value() on string"

Stacktrace:
#10 Error in /Users/paulrobertlloyd/Sites/bradshaws/src/plugins/geo/index.php:48
#9 Kirby\Cms\App:{closure} in /Users/paulrobertlloyd/Sites/bradshaws/vendor/getkirby/cms/src/Toolkit/Collection.php:301
#8 Kirby\Toolkit\Collection:filterBy in /Users/paulrobertlloyd/Sites/bradshaws/src/controllers/search.php:33
#7 Kirby\Cms\App:{closure} in [internal]:0
#6 Closure:call in /Users/paulrobertlloyd/Sites/bradshaws/vendor/getkirby/cms/src/Toolkit/Controller.php:49
#5 Kirby\Toolkit\Controller:call in /Users/paulrobertlloyd/Sites/bradshaws/vendor/getkirby/cms/src/Cms/App.php:376
#4 Kirby\Cms\App:controller in /Users/paulrobertlloyd/Sites/bradshaws/vendor/getkirby/cms/src/Cms/Page.php:347
#3 Kirby\Cms\Page:controller in /Users/paulrobertlloyd/Sites/bradshaws/vendor/getkirby/cms/src/Cms/Page.php:1131
#2 Kirby\Cms\Page:render in /Users/paulrobertlloyd/Sites/bradshaws/vendor/getkirby/cms/src/Cms/App.php:598
#1 Kirby\Cms\App:io in /Users/paulrobertlloyd/Sites/bradshaws/vendor/getkirby/cms/src/Cms/App.php:926
#0 Kirby\Cms\App:render in /Users/paulrobertlloyd/Sites/bradshaws/www/index.php:17
```

**Comment by bastianallgeier** [comment]
I've finally created a new repo for the v3 version of this plugin with the help of your PR 🙌
https://github.com/getkirby/geo

**Pull request closed without merging**
